import { AssetTag, AssetType, MarketingAsset } from './types/asset.types';

export const ASSET_LIBRARY: MarketingAsset[] = [
  {
    id: 'EVE-CS-001',
    title: 'How PI Firms Cut Demand Drafting Time by 75%',
    type: AssetType.CASE_STUDY,
    description:
      'See how a mid-size PI firm reduced demand letter turnaround from days to hours using Eve.',
    ctaLabel: 'Read case study',
    url: 'https://example.eve.legal/assets/demand-drafting-case-study',
    tags: [AssetTag.DEMAND_DRAFTING, AssetTag.FILE_REVIEW],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Mass Tort'],
    targetFirmSizes: ['Mid-Market', 'Enterprise'],
    targetIntakeMethods: ['Phone + Web Form', 'Call center', 'Web chat'],
    targetPainPoints: ['demand drafting', 'file review', 'backlog'],
    targetCaseManagementSystems: ['Litify', 'Clio', 'Filevine'],
    targetLeadStatuses: ['Engaged', 'Warm', 'New'],
    targetEnrichmentSignals: ['hiring', 'verdict', 'growth'],
    baseWeight: 10,
  },
  {
    id: 'EVE-OP-001',
    title: 'After-Hours Intake Playbook for Plaintiff Firms',
    type: AssetType.ONE_PAGER,
    description: 'Capture more qualified leads outside business hours without adding headcount.',
    ctaLabel: 'Download playbook',
    url: 'https://example.eve.legal/assets/after-hours-intake',
    tags: [AssetTag.INTAKE, AssetTag.AFTER_HOURS],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Employment Law'],
    targetFirmSizes: ['Small', 'Mid-Market', 'Enterprise'],
    targetIntakeMethods: ['Phone + Web Form', 'Call center', 'Web chat', 'Referrals'],
    targetPainPoints: ['after-hours', 'intake overflow', 'follow-up'],
    targetCaseManagementSystems: ['Litify', 'Clio', 'Custom CMS'],
    targetLeadStatuses: ['New', 'Nurture', 'Warm'],
    targetEnrichmentSignals: ['office', 'hiring intake'],
    baseWeight: 9,
  },
  {
    id: 'EVE-WB-002',
    title: 'Live Demo: AI Intake Triage for High-Volume Firms',
    type: AssetType.WEBINAR,
    description: 'Watch Eve route, qualify, and summarize inbound leads in real time.',
    ctaLabel: 'Watch webinar',
    url: 'https://example.eve.legal/assets/intake-triage-webinar',
    tags: [AssetTag.INTAKE, AssetTag.CASE_EVALUATION],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Mass Tort'],
    targetFirmSizes: ['Enterprise', 'Mid-Market'],
    targetIntakeMethods: ['Call center', 'Phone + Web Form'],
    targetPainPoints: ['intake overflow', 'case evaluation', 'qualification'],
    targetCaseManagementSystems: ['Litify', 'Filevine'],
    targetLeadStatuses: ['Engaged', 'Warm'],
    targetEnrichmentSignals: ['headcount', 'expanding'],
    baseWeight: 8,
  },
  {
    id: 'EVE-ROI-003',
    title: 'ROI Calculator: Eve vs. Manual File Review',
    type: AssetType.ROI_CALCULATOR,
    description: 'Model attorney hours saved and revenue impact based on your caseload.',
    ctaLabel: 'Calculate ROI',
    url: 'https://example.eve.legal/assets/roi-calculator',
    tags: [AssetTag.FILE_REVIEW, AssetTag.DEMAND_DRAFTING],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Workers Comp', 'Nursing Home'],
    targetFirmSizes: ['Mid-Market', 'Enterprise'],
    targetIntakeMethods: ['Call center', 'Phone + Web Form', 'Referrals'],
    targetPainPoints: ['file review', 'demand drafting', 'review time'],
    targetCaseManagementSystems: ['Litify', 'Clio', 'Filevine', 'Custom CMS'],
    targetLeadStatuses: ['Warm', 'Engaged', 'New'],
    targetEnrichmentSignals: ['private equity', 'growth', 'award'],
    baseWeight: 8,
  },
  {
    id: 'EVE-DV-004',
    title: '2-Minute Product Tour: Eve for Litify Teams',
    type: AssetType.DEMO_VIDEO,
    description: 'See Eve embedded in Litify workflows for intake and drafting.',
    ctaLabel: 'Watch demo',
    url: 'https://example.eve.legal/assets/litify-demo',
    tags: [AssetTag.LITIFY, AssetTag.INTAKE, AssetTag.DEMAND_DRAFTING],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Mass Tort', 'Med Mal'],
    targetFirmSizes: ['Mid-Market', 'Enterprise'],
    targetIntakeMethods: ['Phone + Web Form', 'Call center'],
    targetPainPoints: ['litify', 'integration', 'workflow'],
    targetCaseManagementSystems: ['Litify'],
    targetLeadStatuses: ['Engaged', 'Warm', 'New'],
    targetEnrichmentSignals: ['litify', 'tech stack'],
    baseWeight: 11,
  },
  {
    id: 'EVE-WP-005',
    title: 'Whitepaper: Competing with EvenUp and Supio',
    type: AssetType.WHITEPAPER,
    description: 'A buyer’s guide for plaintiff firms evaluating AI legal tech vendors.',
    ctaLabel: 'Get whitepaper',
    url: 'https://example.eve.legal/assets/competitive-guide',
    tags: [AssetTag.COMPETITOR_DISPLACEMENT, AssetTag.FILE_REVIEW],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Mass Tort'],
    targetFirmSizes: ['Small', 'Mid-Market', 'Enterprise'],
    targetIntakeMethods: ['Phone + Web Form', 'Web chat', 'Referrals'],
    targetPainPoints: ['competitor', 'evaluation', 'ai'],
    targetCaseManagementSystems: ['Litify', 'Clio', 'Filevine', 'Custom CMS'],
    targetLeadStatuses: ['Nurture', 'Warm', 'New'],
    targetEnrichmentSignals: ['evenup', 'supio', 'parrot', 'competitor'],
    baseWeight: 9,
  },
  {
    id: 'EVE-CS-006',
    title: 'Mass Tort Case Study: Scaling Document Review',
    type: AssetType.CASE_STUDY,
    description:
      'How a national PI firm handled a mass tort docket without proportional headcount.',
    ctaLabel: 'Read case study',
    url: 'https://example.eve.legal/assets/mass-tort-case-study',
    tags: [AssetTag.MASS_TORT, AssetTag.FILE_REVIEW],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Mass Tort', 'Personal Injury'],
    targetFirmSizes: ['Enterprise', 'Mid-Market'],
    targetIntakeMethods: ['Call center', 'Phone + Web Form'],
    targetPainPoints: ['mass tort', 'document review', 'scale'],
    targetCaseManagementSystems: ['Litify', 'Filevine'],
    targetLeadStatuses: ['Engaged', 'Warm'],
    targetEnrichmentSignals: ['mass tort', 'acquired', 'expanded'],
    baseWeight: 10,
  },
  {
    id: 'EVE-HB-001',
    title: 'Nursing Home Abuse: Intake Qualification Guide',
    type: AssetType.ONE_PAGER,
    description: 'Structured intake questions and red flags for nursing home abuse matters.',
    ctaLabel: 'Download guide',
    url: 'https://example.eve.legal/assets/nursing-home-intake',
    tags: [AssetTag.NURSING_HOME, AssetTag.INTAKE, AssetTag.CASE_EVALUATION],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Nursing Home', 'Personal Injury'],
    targetFirmSizes: ['Small', 'Mid-Market'],
    targetIntakeMethods: ['Phone + Web Form', 'Referrals', 'Web chat'],
    targetPainPoints: ['intake', 'qualification', 'nursing home'],
    targetCaseManagementSystems: ['Clio', 'Filevine', 'Litify'],
    targetLeadStatuses: ['New', 'Nurture', 'Warm'],
    targetEnrichmentSignals: ['nursing home', 'settled'],
    baseWeight: 7,
  },
  {
    id: 'EVE-BP-002',
    title: 'Trucking Litigation: Demand Package Template Pack',
    type: AssetType.ONE_PAGER,
    description: 'Templates and checklists for trucking case demands and medical chronologies.',
    ctaLabel: 'Get templates',
    url: 'https://example.eve.legal/assets/trucking-templates',
    tags: [AssetTag.TRUCKING, AssetTag.DEMAND_DRAFTING],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Trucking'],
    targetFirmSizes: ['Mid-Market', 'Enterprise'],
    targetIntakeMethods: ['Phone + Web Form', 'Call center'],
    targetPainPoints: ['trucking', 'demand drafting', 'medical chronology'],
    targetCaseManagementSystems: ['Litify', 'Clio', 'Filevine'],
    targetLeadStatuses: ['Engaged', 'Warm', 'New'],
    targetEnrichmentSignals: ['trucking', 'verdict'],
    baseWeight: 8,
  },
  {
    id: 'EVE-OP-004',
    title: 'Clio Integration Overview for Plaintiff Firms',
    type: AssetType.ONE_PAGER,
    description: 'Connect Eve to Clio Grow and matter workflows in under a day.',
    ctaLabel: 'View integration guide',
    url: 'https://example.eve.legal/assets/clio-integration',
    tags: [AssetTag.CLIO, AssetTag.INTAKE],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Employment Law', 'Workers Comp'],
    targetFirmSizes: ['Small', 'Mid-Market'],
    targetIntakeMethods: ['Web chat', 'Referrals', 'Phone + Web Form'],
    targetPainPoints: ['clio', 'integration', 'intake'],
    targetCaseManagementSystems: ['Clio'],
    targetLeadStatuses: ['New', 'Nurture', 'Warm'],
    targetEnrichmentSignals: ['clio', 'tech stack'],
    baseWeight: 10,
  },
  {
    id: 'EVE-WB-003',
    title: 'Growth-Stage Firms: Building an AI-Ready Ops Stack',
    type: AssetType.WEBINAR,
    description: 'Best practices for firms expanding headcount, offices, or practice areas.',
    ctaLabel: 'Register for webinar',
    url: 'https://example.eve.legal/assets/growth-webinar',
    tags: [AssetTag.GROWTH, AssetTag.INTAKE, AssetTag.FILE_REVIEW],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Personal Injury', 'Mass Tort', 'Workers Comp'],
    targetFirmSizes: ['Enterprise', 'Mid-Market'],
    targetIntakeMethods: ['Call center', 'Phone + Web Form'],
    targetPainPoints: ['growth', 'scale', 'headcount'],
    targetCaseManagementSystems: ['Litify', 'Filevine', 'Custom CMS'],
    targetLeadStatuses: ['Engaged', 'Warm'],
    targetEnrichmentSignals: ['acquired', 'office', 'headcount', 'private equity'],
    baseWeight: 7,
  },
  {
    id: 'EVE-CS-007',
    title: 'Workers Comp Expansion: From Intake to Demand in One Platform',
    type: AssetType.CASE_STUDY,
    description: 'How a regional firm launched workers comp with Eve-supported workflows.',
    ctaLabel: 'Read case study',
    url: 'https://example.eve.legal/assets/workers-comp-case-study',
    tags: [AssetTag.WORKERS_COMP, AssetTag.INTAKE, AssetTag.DEMAND_DRAFTING],
    targetIndustries: ['Legal Services'],
    targetPracticeAreas: ['Workers Comp', 'Personal Injury'],
    targetFirmSizes: ['Mid-Market', 'Small'],
    targetIntakeMethods: ['Phone + Web Form', 'Referrals'],
    targetPainPoints: ['workers comp', 'expansion', 'intake'],
    targetCaseManagementSystems: ['Clio', 'Filevine', 'Litify'],
    targetLeadStatuses: ['Warm', 'New', 'Nurture'],
    targetEnrichmentSignals: ['workers comp', 'practice area'],
    baseWeight: 7,
  },
];

export function getAssetById(id: string): MarketingAsset | undefined {
  return ASSET_LIBRARY.find((asset) => asset.id === id);
}
